Print("======================================");
kill(all);
print("ex 3.1");
load("vect");
mu0:4*%pi*10^(-7);
epsilon0:8.85418782*10^(-12);
c:3*10^8;

R1:2000;
R2:8000;
R3:6000;
R4:4000;
vA:4;
vB:6;

eqns: [-1*vA+i1*R1+(i1-i2)*R4+i1*R3=0,(i2-i1)*R4+i2*R2+vB=0];
solve(eqns,[i1,i2]);

vA:4;
vB:0;

eqns: [-1*vA+i1*R1+(i1-i2)*R4+i1*R3=0,(i2-i1)*R4+i2*R2+vB=0];
solve(eqns,[i1,i2]);

vA:0;
vB:6;

eqns: [-1*vA+i1*R1+(i1-i2)*R4+i1*R3=0,(i2-i1)*R4+i2*R2+vB=0];
solve(eqns,[i1,i2]);

